POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 2373
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: securedoc

CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod


EMAIL_HOST: live.smtp.mailtrap.io
EMAIL_PORT: 587
EMAIL_ID: smtp@mailtrap.io
EMAIL_PASSWORD: 61f9641a3f3cba5f81138265fd65523d
VERIFY_EMAIL_HOST: http://localhost:8085