POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 2373
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: securedoc

CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev


EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hvjjj83@gmail.com
EMAIL_PASSWORD: zwwi rkkt ekzy utqf
VERIFY_EMAIL_HOST: http://localhost:8085

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}